import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'CreatorVC',
    short_name: 'CreatorVC',
    description: 'CreatorVC CRM — campaigns, backers, orders.',
    start_url: '/',
    display: 'standalone',
    background_color: '#09090b',
    theme_color: '#09090b',
    orientation: 'portrait',
    icons: [
      // Next 16 serves /icon as a 512×512 PNG generated by app/icon.tsx.
      { src: '/icon', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icon', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      // /apple-icon is the 180×180 iOS-friendly variant.
      { src: '/apple-icon', sizes: '180x180', type: 'image/png' },
    ],
  }
}
