-- Admin + team can create campaigns from the UI. Lives in `public`
-- because that's the schema PostgREST exposes; SECURITY DEFINER so it
-- can write into aa_01_campaigns despite RLS on the underlying table.
--
-- The campaigns.id column is already GENERATED BY DEFAULT AS IDENTITY
-- (sequence aa_01_campaigns.campaigns_id_seq), so the INSERT omits id
-- and Postgres assigns the next value.
--
-- We trim inputs and reject blanks explicitly so the UI gets a clear
-- 22023 (invalid_parameter) error instead of a less-readable 23502
-- (not_null_violation).
CREATE OR REPLACE FUNCTION public.create_campaign(
  p_name text,
  p_legacy_code text
)
RETURNS TABLE(id bigint, name text, legacy_code text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, aa_01_campaigns
AS $$
DECLARE
  v_caller uuid := auth.uid();
  v_role   text;
  v_name   text := nullif(btrim(p_name), '');
  v_code   text := nullif(btrim(p_legacy_code), '');
  v_new_id bigint;
BEGIN
  IF v_caller IS NULL THEN
    RAISE EXCEPTION 'forbidden' USING errcode = '42501';
  END IF;

  SELECT r.role INTO v_role
    FROM public.app_user_roles r
   WHERE r.user_id = v_caller;

  IF v_role IS NULL OR v_role NOT IN ('admin', 'team') THEN
    RAISE EXCEPTION 'forbidden: admin or team only' USING errcode = '42501';
  END IF;

  IF v_name IS NULL THEN
    RAISE EXCEPTION 'name is required' USING errcode = '22023';
  END IF;
  IF v_code IS NULL THEN
    RAISE EXCEPTION 'legacy_code is required' USING errcode = '22023';
  END IF;

  -- legacy_code is a soft-unique key — existing rows all have one and
  -- duplicates would silently confuse downstream joins.
  IF EXISTS (
    SELECT 1 FROM aa_01_campaigns.campaigns c
     WHERE c.legacy_code = v_code
  ) THEN
    RAISE EXCEPTION 'legacy_code already exists: %', v_code USING errcode = '23505';
  END IF;

  INSERT INTO aa_01_campaigns.campaigns ("Name", legacy_code)
  VALUES (v_name, v_code)
  RETURNING aa_01_campaigns.campaigns.id INTO v_new_id;

  RETURN QUERY
    SELECT c.id, c."Name" AS name, c.legacy_code
      FROM aa_01_campaigns.campaigns c
     WHERE c.id = v_new_id;
END;
$$;

REVOKE ALL ON FUNCTION public.create_campaign(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_campaign(text, text) TO authenticated;
